module.exports = {
  TIMESLOT_INTERVAL_MINUTES: 30,
  TIMESLOT_INTERVAL_MILLISECONDS: this.TIMESLOT_INTERVAL_MINUTES * 60000,
  TIMESLOT_NO_SHOW_BUFFER_MINUTES: 15,
  TIMESLOT_NO_SHOW_BUFFER_MILLISECONDS: this.TIMESLOT_NO_SHOW_BUFFER_MINUTES * 60000,
  MAX_BOOKINGS_PER_SLOT: 3,
  DEFAULT_MAX_LOOKAHEAD_HOURS: 10,
  DEFAULT_MAX_LOOKAHEAD_MILLISECONDS: this.DEFAULT_MAX_LOOKAHEAD_HOURS * 3_600_000,
};
