module.exports = {
  TIMESLOT_INTERVAL_MINUTES: 30,
  TIMESLOT_INTERVAL_MILLISECONDS: 30 * 60000,
  TIMESLOT_NO_SHOW_BUFFER_MINUTES: 15,
  TIMESLOT_NO_SHOW_BUFFER_MILLISECONDS: 15 * 60000,
  MAX_BOOKINGS_PER_SLOT: 2,
  DEFAULT_MAX_LOOKAHEAD_HOURS: 10,
  DEFAULT_MAX_LOOKAHEAD_MILLISECONDS: 10 * 3_600_000,
};
